# Generated by Django 5.2.5 on 2025-11-02 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
