# Generated by Django 5.2.5 on 2025-12-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_feature_plan_planfeature_subscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='plan_type',
            field=models.CharField(choices=[('vehicle', 'Vehicle'), ('parts', 'Parts')], default='vehicle', max_length=50),
        ),
    ]
